# Generated by Django 2.1.1 on 2020-05-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotionOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=40)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemAdmin.Package')),
            ],
        ),
    ]
