# Generated by Django 2.1.1 on 2020-05-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemAdmin', '0003_auto_20200506_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='winActivation',
            field=models.CharField(max_length=40),
        ),
    ]
