# Generated by Django 2.1.1 on 2020-05-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=300)),
                ('lastName', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=3000)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('phoneNumber', models.CharField(max_length=40)),
            ],
        ),
    ]
