# Generated by Django 2.1.1 on 2020-05-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userData',
            new_name='CustomerData',
        ),
    ]
